<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 11px;
            line-height: 1.5;
            color: #1e293b;
            margin: 0;
            padding: 0;
            background-color: #ffffff;
        }

        .header {
            padding: 30px 40px;
            border-bottom: 2px solid #0d3b66;
            margin-bottom: 30px;
        }

        .header-content {
            display: table;
            width: 100%;
        }

        .header-left {
            display: table-cell;
            vertical-align: middle;
        }

        .header-right {
            display: table-cell;
            vertical-align: middle;
            text-align: right;
        }

        .logo-text {
            font-size: 28px;
            font-weight: 800;
            color: #0d3b66;
            letter-spacing: -1px;
            margin: 0;
        }

        .report-info {
            color: #64748b;
            font-size: 10px;
            margin-top: 5px;
        }

        .report-title {
            font-size: 20px;
            font-weight: 700;
            color: #0d3b66;
            margin: 0;
        }

        .metric-container {
            display: table;
            width: 100%;
            border-spacing: 15px 0;
            margin: 0 -15px 40px -15px;
        }

        .metric-card {
            display: table-cell;
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 20px;
            text-align: left;
            width: 33.33%;
        }

        .metric-label {
            color: #64748b;
            font-size: 9px;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-bottom: 8px;
        }

        .metric-value {
            font-size: 22px;
            font-weight: 700;
            color: #0d3b66;
        }

        .charts-container {
            display: table;
            width: 100%;
            border-spacing: 15px 0;
            margin: 0 -15px 40px -15px;
        }

        .chart-card {
            display: table-cell;
            width: 50%;
            padding: 0 15px;
        }

        .chart-inner {
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 20px;
        }

        .chart-header {
            font-size: 13px;
            font-weight: 700;
            color: #1e293b;
            margin-bottom: 15px;
            border-left: 4px solid #0d3b66;
            padding-left: 10px;
        }

        .chart-img {
            width: 100%;
            height: auto;
        }

        .table-section {
            margin-top: 20px;
        }

        .table-title {
            font-size: 14px;
            font-weight: 700;
            color: #0d3b66;
            margin-bottom: 15px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th {
            background-color: #f8fafc;
            color: #64748b;
            font-weight: 700;
            font-size: 9px;
            text-transform: uppercase;
            padding: 12px 15px;
            text-align: left;
            border-bottom: 2px solid #e2e8f0;
        }

        td {
            padding: 12px 15px;
            border-bottom: 1px solid #f1f5f9;
            font-size: 10px;
        }

        .amount-col {
            font-weight: 700;
            color: #0d3b66;
        }

        .status-pill {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 9px;
            font-weight: 600;
            background: #dcfce7;
            color: #166534;
        }

        .footer {
            position: fixed;
            bottom: 30px;
            left: 40px;
            right: 40px;
            border-top: 1px solid #e2e8f0;
            padding-top: 15px;
            color: #94a3b8;
            font-size: 9px;
        }

        .page-count:after {
            content: counter(page);
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="header-content">
            <div class="header-left">
                <h1 class="logo-text">OralSync</h1>
                <div class="report-info">Professional Dental Management System</div>
            </div>
            <div class="header-right">
                <div class="report-title">{{ $title }}</div>
                <div class="report-info">
                    Date Range: Last 30 Days | Generated: {{ $generatedAt }}<br>
                    Generated By: {{ $generatedBy }}
                </div>
            </div>
        </div>
    </div>

    <div style="padding: 0 40px;">
        @if(isset($keyMetrics))
        <div class="metric-container">
            @foreach($keyMetrics as $key => $metric)
                @if(is_array($metric))
                <div class="metric-card">
                    <div class="metric-label">{{ $metric['label'] }}</div>
                    <div class="metric-value">{{ $metric['value'] }}</div>
                </div>
                @endif
            @endforeach
        </div>
        @endif

        @if(isset($charts))
        <div class="charts-container">
            @foreach($charts as $id => $chart)
            <div class="chart-card">
                <div class="chart-inner">
                    <div class="chart-header">{{ $chart['title'] }}</div>
                    <img src="{{ $chart['image'] }}" class="chart-img">
                </div>
            </div>
            @endforeach
        </div>
        @endif

        <div class="table-section">
            <div class="table-title">{{ $tableTitle }}</div>
            <table>
                <thead>
                    <tr>
                        @foreach($tableHeaders as $header)
                        <th>{{ $header }}</th>
                        @endforeach
                    </tr>
                </thead>
                <tbody>
                    @foreach($tableData as $row)
                    <tr>
                        @foreach($tableHeaders as $header)
                        <td class="{{ $header === 'Amount' ? 'amount-col' : '' }}">
                            @if($header === 'Status')
                                <span class="status-pill">{{ $row[$header] }}</span>
                            @elseif($header === 'Amount')
                                ₱{{ number_format($row[$header], 2) }}
                            @else
                                {{ $row[$header] }}
                            @endif
                        </td>
                        @endforeach
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <div class="footer">
        <div style="float: left;">© {{ date('Y') }} OralSync Professional Reports. All rights reserved. Confidential.</div>
        <div style="float: right;">Page <span class="page-count"></span></div>
    </div>
</body>
</html>